theme = "apollo"
generate_feeds = true
minify_html = true
taxonomies = [{ name = "tags" }]

# The URL the site will be built for
base_url = "https://pacokwon.org"
title = "Haechan Kwon"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown.highlighting]
style = "class"
light_theme = "catppuccin-latte"
dark_theme = "catppuccin-mocha"

[extra]
toc = true
theme = "toggle"

socials = [
    { name = "github", url = "https://avatars.githubusercontent.com/u/31656049", icon = "github" },
]

menu = [
  { name = "Posts", url = "/posts", weight = 2 },
  { name = "Links", url = "/links", weight = 1 },
]

mathjax = true
mathjax_dollar_inline_enable = true

dynamic_note = true

stylesheets = [
    "posts.css"
]
